FROM golang:1.8.3 as builder
COPY main.go ./
RUN CGO_ENABLED=0 GOOS=linux go build -a -ldflags '-extldflags "-static"' -o /go/bin/https-get .

FROM scratch
COPY --from=builder /go/bin/https-get /https-get
COPY --from=builder /etc/ssl/certs/ /etc/ssl/certs
CMD ["/https-get"]
